### ISSUE TITLE
QA/Phpcs issue

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/integration-with-mautic-for-wp#23]
QA file:
https://docs.google.com/document/d/1CQzluMskYgBI1qiV98CJdgWVHM2gTViRpxLeYr3v-a4/edit?usp=sharing

phpcs file:

[integration-with-mautic-for-wp xml.zip](https://github.com/Makewebbetter/integration-with-mautic-for-wp/files/7076771/integration-with-mautic-for-wp.xml.zip)

**Comment by pranjalshukla-cedcoss** [comment]
All QA issues are now resolved and i have marked in the document as comment which issues are not resolvable.

And all phpcs issues are like before , they all are neglageable except 2-3 issues, because these issues occuring which have to be ignored:
1. Nonce verification (i have put a phpcs ignore comment infront of them).
2. class name should be changed ( as we can't change class name because we have to change class in whole plugin, maybe it will affect some functionality )
3. use escaping function for $helper , because previously it was also ignored because it's data does not escaped .
4. using of extract() function.
5. script must be enqued in forms.php file in public folder, because as src data is dynamic , we can't be able to enqueued script.
