### ISSUE TITLE
QA/phpcs issues

### ISSUE THREAD

**Issue by prateek-cedcoss** [Makewebbetter/integration-with-mautic-for-wp#27]
QA file:
https://docs.google.com/document/d/1kGvZiUePRlsJeXT5KeYNqeC_Hnix_mtpi4I-lvHDEzE/edit?usp=sharing

phpcs file:
[integration-with-mautic-for-wp-xml.zip](https://github.com/Makewebbetter/integration-with-mautic-for-wp/files/7693291/integration-with-mautic-for-wp-xml.zip)

**Comment by pranjalshukla-cedcoss** [comment]
QA issues resolved.

Phpcs issues resolved, but some below listed issues are unresolvable:

1. All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$helper'.
2. extract() usage is highly discouraged, due to the complexity and unintended issues it might cause.
3. Class name is not valid;
4. Scripts must be registered/enqueued via wp_enqueue_script (as there is dynamic script using).
5. Processing form data without nonce verification. ( because we have added comment for phpcs ignore nonce verification )

**Comment by prateek-cedcoss** [comment]
fix
